use_frameworks!

target 'ipv4ipv6Adapter_Example' do
  pod 'ipv4ipv6Adapter', :path => '../'

  target 'ipv4ipv6Adapter_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
